(in-package #:clos-alchemy)

(defun schema-to-json-schema (schema)
  "Translate an ir-schema to a JSON Schema representation (hash table).
The result is directly serializable via yason:encode.
Cyclic schema references are expressed via $defs/$ref."
  (let ((in-progress (make-hash-table :test 'eq))
        (defs (make-hash-table :test 'equal)))
    (let ((result (%ir-schema-to-json-schema schema in-progress defs)))
      (if (zerop (hash-table-count defs))
          result
          (let ((root-name (ir-schema-name schema)))
            (if (gethash root-name defs)
                (let ((wrapper (make-hash-table :test 'equal)))
                  (setf (gethash "$defs" wrapper) defs)
                  (setf (gethash "$ref" wrapper)
                        (format nil "#/$defs/~A" root-name))
                  wrapper)
                (progn
                  (setf (gethash "$defs" result) defs)
                  result)))))))

(defun %ir-schema-to-json-schema (schema in-progress defs)
  (when (gethash schema in-progress)
    (let ((name (ir-schema-name schema))
          (ref-ht (make-hash-table :test 'equal)))
      (setf (gethash name defs) :pending)
      (setf (gethash "$ref" ref-ht) (format nil "#/$defs/~A" name))
      (return-from %ir-schema-to-json-schema ref-ht)))
  (setf (gethash schema in-progress) t)
  (let ((ht (make-hash-table :test 'equal))
        (props (make-hash-table :test 'equal))
        (required '()))
    (setf (gethash "type" ht) "object")
    (dolist (field (ir-schema-fields schema))
      (let ((field-schema
              (let ((base (%ir-type-to-json-schema (ir-field-type field)
                                                    in-progress defs)))
                (if (wire-nullable-p field)
                    (%wrap-nullable base)
                    base))))
        (when (ir-field-description field)
          (setf (gethash "description" field-schema)
                (ir-field-description field)))
        (setf (gethash (ir-field-name field) props) field-schema))
      (push (ir-field-name field) required))
    (setf (gethash "properties" ht) props)
    (setf (gethash "required" ht) (if required (nreverse required) #()))
    (setf (gethash "additionalProperties" ht) 'yason:false)
    (let ((name (ir-schema-name schema)))
      (when (eq (gethash name defs) :pending)
        (setf (gethash name defs) ht)))
    (remhash schema in-progress)
    ht))

(defun %wrap-nullable (type-schema)
  "Wrap a JSON Schema in anyOf [schema, {type: null}]."
  (let ((ht (make-hash-table :test 'equal)))
    (setf (gethash "anyOf" ht)
          (list type-schema
                (let ((null-ht (make-hash-table :test 'equal)))
                  (setf (gethash "type" null-ht) "null")
                  null-ht)))
    ht))

(defun %ir-type-to-json-schema (ir-type in-progress defs)
  (etypecase ir-type
    (ir-type-primitive (%primitive-to-json-schema ir-type))
    (ir-type-enum (%enum-to-json-schema ir-type))
    (ir-type-list (%list-to-json-schema ir-type in-progress defs))
    (ir-type-object (%object-to-json-schema ir-type in-progress defs))
    (ir-type-nullable (%nullable-to-json-schema ir-type in-progress defs))))

(defun %primitive-to-json-schema (ir-type)
  (let ((ht (make-hash-table :test 'equal)))
    (setf (gethash "type" ht)
          (ecase (ir-type-primitive-kind ir-type)
            (:string "string")
            (:integer "integer")
            (:number "number")
            (:boolean "boolean")))
    ht))

(defun %enum-to-json-schema (ir-type)
  (let ((ht (make-hash-table :test 'equal)))
    (setf (gethash "type" ht) "string")
    (setf (gethash "enum" ht) (ir-type-enum-values ir-type))
    ht))

(defun %list-to-json-schema (ir-type in-progress defs)
  (let ((ht (make-hash-table :test 'equal)))
    (setf (gethash "type" ht) "array")
    (setf (gethash "items" ht)
          (%ir-type-to-json-schema (ir-type-list-element-type ir-type)
                                    in-progress defs))
    ht))

(defun %object-to-json-schema (ir-type in-progress defs)
  (%ir-schema-to-json-schema (ir-type-object-schema ir-type) in-progress defs))

(defun %nullable-to-json-schema (ir-type in-progress defs)
  (let ((ht (make-hash-table :test 'equal)))
    (setf (gethash "anyOf" ht)
          (list (%ir-type-to-json-schema (ir-type-nullable-inner-type ir-type)
                                          in-progress defs)
                (let ((null-ht (make-hash-table :test 'equal)))
                  (setf (gethash "type" null-ht) "null")
                  null-ht)))
    ht))
