(in-package #:clos-alchemy)

(defclass constructor-class (standard-class)
  ()
  (:documentation "Metaclass supporting :list-of as a custom slot option."))

(defmethod closer-mop:validate-superclass ((class constructor-class)
                                           (superclass standard-class))
  t)

(defclass constructor-direct-slot-definition
    (closer-mop:standard-direct-slot-definition)
  ((list-of            :initarg :list-of            :initform nil :reader slot-definition-list-of)
   (map-of             :initarg :map-of             :initform nil :reader slot-definition-map-of)
   (validate           :initarg :validate           :initform nil :reader slot-definition-validate)
   (minimum            :initarg :minimum            :initform nil :reader slot-definition-minimum)
   (maximum            :initarg :maximum            :initform nil :reader slot-definition-maximum)
   (exclusive-minimum  :initarg :exclusive-minimum  :initform nil :reader slot-definition-exclusive-minimum)
   (exclusive-maximum  :initarg :exclusive-maximum  :initform nil :reader slot-definition-exclusive-maximum)
   (min-length         :initarg :min-length         :initform nil :reader slot-definition-min-length)
   (max-length         :initarg :max-length         :initform nil :reader slot-definition-max-length)
   (pattern            :initarg :pattern            :initform nil :reader slot-definition-pattern)
   (min-items          :initarg :min-items          :initform nil :reader slot-definition-min-items)
   (max-items          :initarg :max-items          :initform nil :reader slot-definition-max-items)))

(defclass constructor-effective-slot-definition
    (closer-mop:standard-effective-slot-definition)
  ((list-of            :initarg :list-of            :initform nil :reader slot-definition-list-of)
   (map-of             :initarg :map-of             :initform nil :reader slot-definition-map-of)
   (validate           :initarg :validate           :initform nil :reader slot-definition-validate)
   (minimum            :initarg :minimum            :initform nil :reader slot-definition-minimum)
   (maximum            :initarg :maximum            :initform nil :reader slot-definition-maximum)
   (exclusive-minimum  :initarg :exclusive-minimum  :initform nil :reader slot-definition-exclusive-minimum)
   (exclusive-maximum  :initarg :exclusive-maximum  :initform nil :reader slot-definition-exclusive-maximum)
   (min-length         :initarg :min-length         :initform nil :reader slot-definition-min-length)
   (max-length         :initarg :max-length         :initform nil :reader slot-definition-max-length)
   (pattern            :initarg :pattern            :initform nil :reader slot-definition-pattern)
   (min-items          :initarg :min-items          :initform nil :reader slot-definition-min-items)
   (max-items          :initarg :max-items          :initform nil :reader slot-definition-max-items)))

(defmethod closer-mop:direct-slot-definition-class ((class constructor-class)
                                                     &rest initargs)
  (declare (ignore initargs))
  (find-class 'constructor-direct-slot-definition))

(defmethod closer-mop:effective-slot-definition-class ((class constructor-class)
                                                       &rest initargs)
  (declare (ignore initargs))
  (find-class 'constructor-effective-slot-definition))

(defmethod closer-mop:compute-effective-slot-definition
    ((class constructor-class) name direct-slot-definitions)
  (declare (ignore name))
  (macrolet ((propagate (slot-name accessor)
               `(let ((val (loop for dsd in direct-slot-definitions
                                 when (and (typep dsd 'constructor-direct-slot-definition)
                                           (,accessor dsd))
                                   return (,accessor dsd))))
                  (when val
                    (setf (slot-value effective-slot ',slot-name) val)))))
    (let ((effective-slot (call-next-method)))
      (propagate list-of slot-definition-list-of)
      (propagate map-of slot-definition-map-of)
      (propagate validate slot-definition-validate)
      (propagate minimum slot-definition-minimum)
      (propagate maximum slot-definition-maximum)
      (propagate exclusive-minimum slot-definition-exclusive-minimum)
      (propagate exclusive-maximum slot-definition-exclusive-maximum)
      (propagate min-length slot-definition-min-length)
      (propagate max-length slot-definition-max-length)
      (propagate pattern slot-definition-pattern)
      (propagate min-items slot-definition-min-items)
      (propagate max-items slot-definition-max-items)
      effective-slot)))
